### ISSUE TITLE
"enable_segmentation" is always true on transit

### ISSUE THREAD

**Issue by jwang-avx** [terraform-aviatrix-modules/terraform-aviatrix-mc-transit-deployment-framework#1]
In 6.8 dev controller, I created transit network with default segmentation setting, but noticed all transits have segmentation enabled. I explicitly disabled it with "transit_enable_segmentation = false", but terraform will ignore it. Let me know if you need further information of the setup. Thanks.

**Comment by Dennizz** [comment]
Try:
`transit_segmentation = false`

I think I may have documented this incorrectly. (name of argument as well as default value)

**Comment by jwang-avx** [comment]
Bingo! That works. Much appreciated.

**Comment by Dennizz** [comment]
Great, I will leave this issue open until I address the documentation.

**Comment by Dennizz** [comment]
Addressed in docs
