### ISSUE TITLE
Missing arguments with internal dev aviatrix provider

### ISSUE THREAD

**Issue by jwang-avx** [terraform-aviatrix-modules/terraform-aviatrix-mc-transit-deployment-framework#2]
With internal dev aviatrix provider:
`terraform {
  required_providers {
    aviatrix = {
      source  = "aviatrix.com/aviatrix/aviatrix"
      version = "99.0.0"
    }
  }
  required_version = ">= 0.14"
}`
Terraform apply always fails with the following errors:
`│ Error: Missing required argument
│ 
│ The argument "username" is required, but was not set.
╵
╷
│ Error: Missing required argument
│ 
│ The argument "controller_ip" is required, but was not set.`

**Comment by Dennizz** [comment]
Is this even happening while having the [authentication](https://registry.terraform.io/providers/AviatrixSystems/aviatrix/latest/docs#authentication) set up?

**Comment by jwang-avx** [comment]
Yes. If I change to published provider versions, e.g. 2.21.1, the code will work. Other people has seen similar issue in their setup.

**Comment by Dennizz** [comment]
I expect that your `terraform providers` output shows the modules using the regular provider rather than the compiled 99.0.0. If you need to use the modules in development, I'm afraid you would have to override the version constrains in all modules to use the 99.0.0 provider.

**Comment by jwang-avx** [comment]
Thanks Dennis. That's fine. I can checkout the modules to local and update the versions.
