### ISSUE TITLE
Missing transit_enable_active_standby

### ISSUE THREAD

**Issue by pawelfraczyk** [terraform-aviatrix-modules/terraform-aviatrix-mc-transit-deployment-framework#8]
Hello,

I can't enable active-standby on Transit Gateway.
Docs: https://docs.aviatrix.com/documentation/v7.0/building-your-network/bgp-connection-settings.html#active-standby

I see module has only:
- transit_enable_active_standby_preemptive
Setting this option to 'true' will still show Terraform plan to keep value of enable_active_standby as false.

![image](https://github.com/terraform-aviatrix-modules/terraform-aviatrix-mc-transit-deployment-framework/assets/56155290/ef12cb7b-96d3-4bc3-9721-d63e990182e1)

Can you add this property e.g. transit_enable_active_standby to pass it down to the module of transit gateway?

**Comment by pawelfraczyk** [comment]
Apply shows an error:
![image](https://github.com/terraform-aviatrix-modules/terraform-aviatrix-mc-transit-deployment-framework/assets/56155290/c67564b6-612c-44eb-9935-f9dbf9ed136f)

**Comment by Dennizz** [comment]
Hi Pawel, happy to add this. This module was moved to https://github.com/terraform-aviatrix-modules/terraform-aviatrix-backbone a little while a go. Can you migrate that that module for future support please and raise the issue against that repo?

Please let me know which software version you need this against, so I can release the module backward compatible with that release.
