### ISSUE TITLE
Missing transit_enable_active_standby for transit gateway submodule

### ISSUE THREAD

**Issue by pawelfraczyk** [terraform-aviatrix-modules/terraform-aviatrix-mc-transit-deployment-framework#9]
Hello,

I can't enable active-standby on Transit Gateway.
Docs: https://docs.aviatrix.com/documentation/v7.0/building-your-network/bgp-connection-settings.html#active-standby

I see module has only:

transit_enable_active_standby_preemptive
Setting this option to 'true' will still show Terraform plan to keep value of enable_active_standby as false and fail to deploy. See attached screen.

![image](https://github.com/terraform-aviatrix-modules/terraform-aviatrix-mc-transit-deployment-framework/assets/56155290/ee63640b-a385-495b-8b3c-a4738b243cb0)

Can you add this property e.g. transit_enable_active_standby to pass it down to the module of transit gateway?

**Comment by pawelfraczyk** [comment]
Sorry I just realized I did it on the same repo :(

I can't raise the Issue on the new one.

**Comment by Dennizz** [comment]
For some reason issues was disabled on that repo. Should be fixed. Please try again. Please include the controller/provider version you require this for.

Thanks,

Dennis
